<x-admin-layout>
    hola desde dashboard

    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
    <h2>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Deleniti temporibus provident officia beatae quod quibusdam harum nihil quas voluptas fuga reprehenderit inventore in eveniet, vel non odit cupiditate? Consectetur, doloribus.</h2>
</x-admin-layout>
